name: Translate MD Action
author: DLIOCode
description: Translate the Readme to another language

inputs:
  LANG_FROM:
    description: 'The language your readme is in'
    required: true
    default: 'en'

  LANG_TO:
    description: 'The Language you want to translate to'
    required: true
    default: 'pt'
   
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: book-open
  color: black
